PREFIX : <http://dbpedia.org/resource/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX dbo: <http://dbpedia.org/ontology/>
SELECT ?author_name ?title ?pages
FROM <http://dbpedia.org/>
WHERE {
?author rdf:type dbo:Writer . ?author rdfs:label ?author_name FILTER (LANG(?author_name)="en"). ?author dbo:notableWork ?work . ?work dbo:numberOfPages ?pages . FILTER (?pages > 500)
       ?work rdfs:label ?title .
FILTER (LANG(?title)="en") } LIMIT 100
