PREFIX : <http://dbpedia.org/resource/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX dbo: <http://dbpedia.org/ontology/>
SELECT ?influencer ?influenced FROM <http://dbpedia.org/> WHERE {
   { :Jules_Verne dbo:influenced ?influenced . }
UNION
   { :Jules_Verne dbo:influencedBy ?influencer . }
}
